### ISSUE TITLE
pre signed url in not valid after 1 hour

### ISSUE THREAD

**Issue by Sree1894** [nimran/Amazon-S3-Integration-in-Android#2]
Hi
 After adding image in s3 i am getting a presigned urlbut this pre signed url gets expired after one hour showing token expiration .i need to generate a presigned url with unlimited token experiation time.
                                                                    thank you

**Comment by nimran** [comment]
https://github.com/nimran/Amazon-S3-Integration-in-Android/blob/master/app/src/main/java/study/amazons3integration/aws/S3Utils.java  

Under generates3ShareUrl() modify as per your requirement.

       

>  Date expiration = new Date();
>         long msec = expiration.getTime();
>         msec += 1000 * 6000 * 6000; // 1 hour.
>         Date d = new Date();
