### ISSUE TITLE
How to upload Pdf

### ISSUE THREAD

**Issue by debasishappsbee** [nimran/Amazon-S3-Integration-in-Android#3]
Hi, nimran,
I have integrated Amazon s3 also uploading images to s3 works fine. Can you please tell me how can I upload pdf or any other file into s3?

**Comment by nimran** [comment]
In the MainActivity.kt, under file chooser change the mime type..
I have hardcoded as image.
You can change to pdf or doc as per your requirement.  This is just a sample and not a library. Hence I have coded only for image.

**Comment by debasishappsbee** [comment]
Thanks for your replay, yes I have done that but I was getting an invalid uri path, that is resolved now. Thanks
